import Head from "next/head";

import Componente from "@/components/Componente"
import Contatore from "@/components/Contatore"
import Lampadina from "@/components/Lampadina"
import data from "@/data/data";

export default function Home() {

  const x = 42;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Componente proprieta={x} />
      <Contatore />
      <Lampadina />
    </>
  );
}
