import Head from "next/head";

import Componente from "@/components/Componente"
import Contatore from "@/components/Contatore"
// import Lampadina from "@/components/Lampadina"
import LampadinaConInterruttore from "@/components/LampadinaConInterruttore"
import ControlledInput from "@/components/ControlledInput"
import ToDoList from "@/components/ToDoList"


import data from "@/data/data";

import { useState } from "react";

export default function Home() {

  const x = 42;

  const [isOn, setIsOn] = useState(true);

  // function toggleLampadina() {
  //   setIsOn(!isOn);
  // }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Componente proprieta={x} />
      <Contatore />

      {/* <Lampadina isOn={isOn} />
      <button onClick={toggleLampadina}>{isOn ? "Spegni" : "Accendi"}</button> */}

      <LampadinaConInterruttore />

      <ControlledInput />

      <ToDoList />

    </>
  );
}
